minor

diff --git a/.github/workflows/CI_CD.yml b/.github/workflows/CI_CD.yml
--- a/.github/workflows/CI_CD.yml
+++ b/.github/workflows/CI_CD.yml
@@ -34,8 +34,10 @@ jobs:
 
           # SSH into the EC2 instance and deploy the React app
           ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
+            set -e  # Stop the script if any command fails
+
             # Navigate to the workspace folder
-            cd /home/ubuntu/workspace  # Corrected the path to use a space between `cd` and the path
+            cd /home/ubuntu/workspace
 
             # Check if the project directory exists. If not, clone the repository.
             if [ ! -d "/home/ubuntu/workspace/shope-ease/.git" ]; then
@@ -68,8 +70,7 @@ jobs:
             # Update Nginx config to point to the React dist directory
             echo "server {
                 listen 80;
-                server_name 44.194.3.239;
-
+                server_name 44.194.3.239;  
                 root /home/ubuntu/workspace/shope-ease/dist;
                 index index.html;
 
@@ -86,8 +87,8 @@ jobs:
             # Test Nginx configuration
             sudo nginx -t
 
-            # Reload Nginx to apply new config
-            sudo systemctl reload nginx
+            # Restart Nginx to apply new config
+            sudo systemctl restart nginx
 
             # Optionally, check the status of Nginx to ensure it's running correctly
             sudo systemctl status nginx
